[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "16"
  REACT_APP_FIREBASE_API_KEY = "AIzaSyByIUq4XM1FEAW53sIXMWHujFRRm4dgchU"
  REACT_APP_FIREBASE_AUTH_DOMAIN = "chat-app-f36fe.firebaseapp.com"
  REACT_APP_FIREBASE_DATABASE_URL = "https://chat-app-f36fe-default-rtdb.asia-southeast1.firebasedatabase.app"
  REACT_APP_FIREBASE_PROJECT_ID = "chat-app-f36fe"
  REACT_APP_FIREBASE_STORAGE_BUCKET = "chat-app-f36fe.firebasestorage.app"
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID = "529322077582"
  REACT_APP_FIREBASE_APP_ID = "1:529322077582:web:c61c0e2d69c504631b08df"
  
  # Firebase Admin SDK 환경 변수 (서버리스 함수용)
  FIREBASE_PROJECT_ID = "chat-app-f36fe"
  FIREBASE_DATABASE_URL = "https://chat-app-f36fe-default-rtdb.asia-southeast1.firebasedatabase.app"
  # 아래 값들은 실제 서비스 계정 키 값으로 대체해야 합니다
  # FIREBASE_PRIVATE_KEY_ID = "서비스 계정 키 ID"
  # FIREBASE_PRIVATE_KEY = "서비스 계정 개인 키"
  # FIREBASE_CLIENT_EMAIL = "서비스 계정 이메일"
  # FIREBASE_CLIENT_ID = "서비스 계정 클라이언트 ID"
  # FIREBASE_CLIENT_CERT_URL = "서비스 계정 인증서 URL"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Firebase 관련 CORS 헤더 설정
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"

# 캐시 설정 - 정적 자산은 캐시하지만 HTML은 항상 최신 버전
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Netlify 함수 설정
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
